name: Build and Release Docker Image

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # semantic-release için zorunlu

      - name: Set lowercase owner
        id: vars
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: semrel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Log release info
        run: |
          echo "Published? ${{ steps.semrel.outputs.new_release_published }}"
          echo "Version: ${{ steps.semrel.outputs.new_release_version }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ steps.semrel.outputs.new_release_published == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/monolith-api:latest
            ghcr.io/${{ env.OWNER_LC }}/monolith-api:v${{ steps.semrel.outputs.new_release_version }}
